### ISSUE TITLE
New EULAs required (region DE) 

### ISSUE THREAD

**Issue by ogsadmin** [timoschlueter/nightscout-librelink-up#100]
Hi,

starting tonight (2022-06-14), nightscout-librelink-up was not able to get readings from the libre site - the error message indicated, that new EULAs need to be accepted (exactly the same issue as reported in #33, the error response included `"componentName"="AcceptDocument"`). 

To solve this problem, one needs to accept the EULAs, which is (at least for me) not a  straightforward process, as the LibreLinkUp app (in my case for Android) continues to work correctly and does not show any indication of this situation. 

For my reference (and for others), here is a short description on the steps needed to solve this:

Steps:

1. Open LibreLinkUp on your Android phone
2. Open the hamburger menu, on the top left, select settings --> account
3. Tap the ... menu on the top right of the settings page and select logoff
4. Login again (it should immediately prompt you)
5. Accept the new EULA

At the next polling cycle, nightscout-librelink-up will be able to successfully get readings from the libre site again.

@timoschlueter: As this seems to happen from time to time, maybe you can add some information to the README.md?

Thanks!

**Comment by timoschlueter** [comment]
Hi! I will add this to the README in the next release. Thank you! :)

**Comment by zreptil** [comment]
Thanks for this guide, but at my site it still doesn't work. I opened an issue at ns10be, but still no information whats going wrong there. I even did the following:

1. creating an brandnew user at libreview.de
2. accepting all eulas, datasecurity ... whatever you have to click, i clicked it
3. inviting this new account with my freestlye libre 3 app on the android smartphone under linked apps
4. opening up librelinkup on my smartphone 
5. logging in with the account
6. accepting everything that has to be accepted
7. seeing all values as before in the other account
8. heading over to ns10be
9. editing my server
10. entering the new account information in the librelinkup plugin
11. restarting the server
12. redeploying the serrver
13. still no readings in nioghtscout

what else can i do to have this working again?

**Comment by ogsadmin** [comment]
I guess this is related to #99. 

My uploader is also not able to connect to the Libre servers anymore since around 11pm yesterday - but with a different error (not the EULA issue). As I've received an update notification for the LibreLinkUp Android app today, I assume they changed something (app date is 2022-06-02).

I'll post my findings to #99, maybe @timoschlueter can help.

**Comment by mduiella** [comment]
Thanks so much! 
since 3 am last night, nightscout-librelink-up was no longer able to access readings from LibreLink Up (while these were showing correctly in the Libre app). I was getting the following as error message: `LibreLink Up - No AuthTicket received. Please check your credentials. `
Updating the password didn't solve anything...
Your instructions (logging out and in again from the LibreLink Up app and (re-)accepting the end user license agreement) miraculously fixed it!
