### ISSUE TITLE
can I set this up for free????

### ISSUE THREAD

**Issue by dummdogggg** [timoschlueter/nightscout-librelink-up#123]
can I set this up for free? if were and how.
(try doing it but get [error]: LibreLink Up - Non-zero status code: {"status":2,"error":{"message":"notAuthenticated"}}
[error]: LibreLink Up - No AuthTicket received. Please check your credentials.)

**Comment by HammyHavoc** [comment]
Yes, did you get it sorted out?

**Comment by dummdogggg** [comment]
> Yes, did you get it sorted out?

no

**Comment by HammyHavoc** [comment]
How far did you get?

**Comment by dummdogggg** [comment]
well i kinda gave up bc i am getting a new sensor in 2 weeks. but thanks for asking
