### ISSUE TITLE
How do I  know if its working or properly installed ? No data after 20 minutes !

### ISSUE THREAD

**Issue by sircsaba** [timoschlueter/nightscout-librelink-up#126]
Hello,

I just installed nightscout 14.2.6 on a Pi4. The instalation went well using Portainer/Docker. This is also how I installed the this image and script. 
Everything looks good on Portainer and I have nightscout open but there's no data coming in. My librelinkup on my phone ()Android) is receiving data but nothing in nightscout !!

This is the script in my Stack with the personal info blocked out : 

version: '3.7'
services:
  nightscout-libre-link:
    image: timoschlueter/nightscout-librelink-up
    container_name: nightscout-libre-link
    environment:
      LINK_UP_USERNAME: "jack@jack.com"
      LINK_UP_PASSWORD: "jack"
      LINK_UP_TIME_INTERVAL: "5"
      LINK_UP_REGION: "CA"
      NIGHTSCOUT_URL: "12.34.56.789:1234"
      NIGHTSCOUT_API_TOKEN: "jackandthebeanstock"
      NIGHTSCOUT_DISABLE_HTTPS: "true"
      LOG_LEVEL: "info"

Using my nightscout url, nightscout opens up. I haven't done a DDNS yet but that will come ....

Where in nightscout can I see this working or activated if possible ??

Any insight would be greatly appreciated !

Sincerely

**Comment by timoschlueter** [comment]
Can you give us the output that you see on the container in portainer? The console logs would help a lot!

**Comment by sircsaba** [comment]
I was finally able to figure it out. I had to create a token with the appropriate function. Thanks for answering back !
