### ISSUE TITLE
New Location - LA

### ISSUE THREAD

**Issue by diego-castilho** [timoschlueter/nightscout-librelink-up#148]
I edit file src/constants/llu-api-endpoints.ts, include `LA: "api-la.libreview.io",` in the list, change the env variable to `LINK_UP_REGION: "LA"` and build a local image.

Work fine for me in Brazil.

> Hi, all.
> About 9 hours ago I started to receive this message:
> 
> [info]: renew token
> [error]: LibreLink Up - Logged in to the wrong region. Switch to 'LA' region.                                                                                                  [error]: LibreLink Up - No AuthTicket received. Please check your credentials.
> 
> 
> I tried logging off and logging on LibreLinkUP and accepting new terms, but it didn't work. I tried to follow the message and change the region to LA, but I received LA is not a supported region.
> 
> I'm from Brazil.
> 
> _Originally posted by @diego-castilho in https://github.com/timoschlueter/nightscout-librelink-up/issues/143#issuecomment-2194383720_
>

**Comment by gui-dos** [comment]
If you request `https://api.libreview.io/llu/config/country?country=BR` you can get dynamically the subdomain to use by extracting with the entry

`"lslApi":"https://api-la.libreview.io/`

**Comment by timoschlueter** [comment]
@diego-castilho your PR has been merged and the new Endpoint is available in v2.7.0. Thank you very much! :)
