### ISSUE TITLE
Minimum LibreLinkUp version

### ISSUE THREAD

**Issue by dc00l** [timoschlueter/nightscout-librelink-up#167]
Abbott seems to raised the minimum for Libre LinkUp to 4.12. Since the string is hardcoded in index.ts could you please update it?

**Comment by vanzaam** [comment]
if only change version in the index.ts to 4.12.0 - :

```
[error]: {"message":"RequiredHeaderMissing"}
[error]: getting libreLinkUpConnection:  Cannot read properties of undefined (reading 'data')
```

**Comment by timoschlueter** [comment]
Looks like Abbott has added some checks to their endpoints. I guess i have to re-analyse the app traffic again.
Unfortunately, I wont be able to do so until this evening.

**Comment by chucker** [comment]
Haven't looked into it much, but it seems the official app now sets an `Account-Id` header (which looks like a SHA256?). Looks like #155 already prepares that?

**Comment by dc00l** [comment]
Account-Id is correct. Was not just SHA256 of the user, but did not dig into it. I had to get the loop up and running and hardcoded the Account-Id from the libreview login. Now it works. Will have a look later.

**Comment by timoschlueter** [comment]
Fixed in Version 2.7.2.
Enjoy :)

**Comment by dc00l** [comment]
Works, great, Have a brilliant weekend.

**Comment by melwaraki** [comment]
I wish I saw this post before pulling at my hair for hours and finally fixing it in my app 😂

**Comment by miguefl** [comment]
It's happening to me running the version 2.7.3

https://github.com/timoschlueter/nightscout-librelink-up/issues/176

more logs:

```
nightscout-librelink-up@2.7.3 start /home/user/nightscout-librelink-up
> npx ts-node --transpile-only src/index.ts

[info]: Starting cron schedule: */2 * * * *
[info]: renew token
[info]: Logged in to LibreLink Up
[error]: Error getting accountId:  Invalid token specified: invalid base64 for part #2 (atob is not defined)
[error]: {"message":"RequiredHeaderMissing"}
[error]: getting libreLinkUpConnection:  Cannot read property 'data' of undefined
[info]: renew token
[info]: Logged in to LibreLink Up
[error]: Error getting accountId:  Invalid token specified: invalid base64 for part #2 (atob is not defined)
[error]: {"message":"RequiredHeaderMissing"}
[error]: getting libreLinkUpConnection:  Cannot read property 'data' of undefined
[info]: renew token
[info]: Logged in to LibreLink Up
[error]: Error getting accountId:  Invalid token specified: invalid base64 for part #2 (atob is not defined)
[error]: {"message":"RequiredHeaderMissing"}
[error]: getting libreLinkUpConnection:  Cannot read property 'data' of undefined
[info]: renew token
[info]: Logged in to LibreLink Up
[error]: Error getting accountId:  Invalid token specified: invalid base64 for part #2 (atob is not defined)
[error]: {"message":"RequiredHeaderMissing"}
[error]: getting libreLinkUpConnection:  Cannot read property 'data' of undefined
```
