### ISSUE TITLE
Freestyle Libre 2 scanning

### ISSUE THREAD

**Issue by adarbac** [timoschlueter/nightscout-librelink-up#20]
Does it work with Freestyle Libre 2 without repetitive NFC scanning?

**Comment by timoschlueter** [comment]
Unfortunately not. All this tool does is pulling data from LibreLink Up and uploading it to Nightscout. If there is no data in LLU, there is nothing to upload. With Libre 2 you need to scan in order to upload data to LLU. Therefore this is still a requirement. :/
