### ISSUE TITLE
Cross Sync with Mysugr and others

### ISSUE THREAD

**Issue by yoshimo** [timoschlueter/nightscout-librelink-up#26]
The basic idea is interesting.
Some people prefer a nice App like mysugr that collects a few more data pieces.
Some doctors prefer Libreview, some other systems.
Are you intrested in creating a solution that pulls data from multiple sources, combines them, denoises them and uploads the merged data to connected services?
This would make it a lot easier to maintain data for the end user

**Comment by timoschlueter** [comment]
I don't think this is in the scope for this project. The concept of nightscout is really promising to achieve what you are suggesting, actually. Having nightscout as the single, self-hosted source of truth with the right integration into Health Kit (at least on iPhones) would come very close to such a solution.
I am currently using [Nightguard](https://github.com/nightscout/nightguard/issues/101) as a client for my Nightscout instance and all thats missing is that Nightguard needs to sync to Apple Health (Spoiler: [its coming](https://github.com/nightscout/nightguard/issues/101)).

If that is integrated, my setup would be the following:

Libre 3 Sensor -> LibreLink Up -> *This App* -> Nightscout -> Nightguard (iPhone) -> Apple Health -> mySugr

This works for iPhone of course. But a solution for Android should not be too far off.
