### ISSUE TITLE
Invalid credentials / 401

### ISSUE THREAD

**Issue by marcograwunder** [timoschlueter/nightscout-librelink-up#39]
Hi, thank you very much for your project. 

I used some parts in a private system (with iobroker) to get the glucose data of my son. Since yesterday evening, I cannot login any more. It seems to be a 401 response ("Request failed with status code 401"), I've already created another user to watch, but still the same. The login method is (nearly) identical to yours.

I just want to know, if the error/problem is on my side, or did Abbott changed anything? As I am using an iPhone with LibreLinkUp (where both accounts are working without any problems) I cannot watch the (encrypted) network traffic.

**Comment by timoschlueter** [comment]
hi @marcograwunder, I have not noticed any problems yet. The LibreLink Up servers were in maintenance mode a few times over the last couple of days. Have you checked again if it works now?

**Comment by marcograwunder** [comment]
Thank you for your reply. Then I will need to check, if there is an error in my still not working code.
