### ISSUE TITLE
Floating average

### ISSUE THREAD

**Issue by Jonaskjellsson** [timoschlueter/nightscout-librelink-up#41]
Hi me and my daughter would love to have a feature with floating average. You can have a variable on how many of the most recent values are calculated 2-6 maybe?

Libre is a bit sensitive if you lie on it, it quickly dips down 2-3 mmol and low alarms come unnecessarily.

Thanks

**Comment by timoschlueter** [comment]
We will track this improvement in #78. Closing this for consolidation.
