### ISSUE TITLE
Using dedicated client and implement only bridge functionality for nightscout

### ISSUE THREAD

**Issue by khskekec** [timoschlueter/nightscout-librelink-up#44]
Hi @timoschlueter,

Thanks for your excellent work and giving people the opportunity to feed there nightscout instance with Libre 3 data.

For this simple purpose I have also implemented a basic client to retrieve libre 3 data: https://github.com/DiaKEM/libre-link-up-api-client

Maybe it is an option for you to reuse it here and implement only the Middleware to pass data to nightscout to reduce the needed code. It is only an idea 😉.

Viele Grüße 😀

Selçuk

**Comment by timoschlueter** [comment]
Hi Selçuk, glad to see that I am not the only one working on this problem :)
For now, I would keep things the way they are but I will subscribe to your project in order to stay up to date. I am sure I will come back to this later :)
