### ISSUE TITLE
Docker container for Raspberry Pi

### ISSUE THREAD

**Issue by cubybox** [timoschlueter/nightscout-librelink-up#45]
Hi Timo, 

do you think it is possible to create the Docker container for arm64 in addition to the amd64 platform? Then you could run the whole thing very energy-efficiently on a Raspberry Pi.

Many greets
Dirk

**Comment by khskekec** [comment]
Hi Dirk,

I am really interested to this topic also and am confused now. I thought that this should be also possible with the current image.

Do you fear incompatibility or would wish a more performant image?

Kind regards

Selçuk

**Comment by cubybox** [comment]
Hi Selçuk,

unfortunately it is not compatible. Until then I also thought that a Docker container runs on any platform. Unfortunately that is not the case. In this case you get the following error message:

_WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested._

greeting
dirk

**Comment by khskekec** [comment]
Hi Dirk,

I read something about problems on arm based archs and docker. There might be a problem to recognize the needed platform image correctly.

Can you try to define the arch explicitly like:

```
FROM --platform=linux/arm64/v8 node
```

Unfortunately I do not have a rpi actually which is up and running.

Would be great if you can give me some feedback 😊.

Kind regards

Selçuk

**Comment by cubybox** [comment]
Hi Selçuk,

I've already tried that. Unfortunately does not work.
Then the only way left is to define the Docker container for multiplatform. Then it should work.

For now, I've done a setup at heroku.com. Works well and I don't have to leave the Windows PC running 24 hours a day. But I'm still interested in getting the whole thing to run on a Pi ;-)

greets
Dirk

**Comment by marcograwunder** [comment]
You could just run docker create (https://docs.docker.com/engine/reference/commandline/create/) with the given dockerfile directly on the raspberry pi. Then a Arm-based image is created and can be used there.

**Comment by timoschlueter** [comment]
I just release version 1.7.1 with support for ARM64 platforms. :)
Feel free to try it on your RPi @cubybox.

**Comment by timoschlueter** [comment]
I added version 1.7.2 with support for ARMv7 (Raspberry Pi 3). Was able to run it on my device. I don't have a RPi 4 available for testing but on the RPi 3 the container runs just fine. :)

**Comment by cubybox** [comment]
Hi Timo,

it runs great on an old raspberry PI3 that I still had here. Many thanks for the quick help!

All data is uploaded correctly to nightscout - but the same error message keeps appearing in the log. In addition, the number of uploaded BG values ​​in the log does not seem to be correct:

`2022-06-14T21:37:02.101357111Z [info]: Received blood glucose measurement items`
`2022-06-14T21:38:03.215503542Z [error]: "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.21.6</center>\r\n</body>\r\n</html>\r\n"`
`2022-06-14T21:39:03.335260470Z [info]: Upload of 0 measurements to NightScout succeeded
`

Many greetings
Dirk
