### ISSUE TITLE
error code=H10 desc="App crashed"

### ISSUE THREAD

**Issue by MaxPressure** [timoschlueter/nightscout-librelink-up#46]
Hi Timo, 

First, thanks for having posted this script. 

I have deployed it on Heroku, double checked variables, hashed Nightscout password as requested, but I keep on logging the following error:

2022-06-12T14:50:00.688125+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/api/v1/entries" host=<removed>.herokuapp.com request_id=d2e00448-58fa-4726-abd4-7fce16876b3a fwd="54.228.36.199" dyno= connect= service= status=503 bytes= protocol=https

Any idea ?

Thanks

Andrea

**Comment by cubybox** [comment]
Hi Andrea,

you have to hash the API-token - not the password. Could that be the problem?
I have used this generator and it works with it:

[sha generator](https://www.sha1-generator.info/was-ist-der-sha1-hash#:~:text=Der%20Secure%20Hash%20Algorithm%20(SHA1,20%2Dbyte)%2DHashwert%20erzeugt.)

greets 
Dirk

**Comment by MaxPressure** [comment]
Hi Dirk, 
Thanks for your input, it really drove me in the right direction. 
Actually , I now receive FSL3 BG readings on Nightscout.
Regards
Andrea
