### ISSUE TITLE
Import trend/direction from LibreLink Up

### ISSUE THREAD

**Issue by timoschlueter** [timoschlueter/nightscout-librelink-up#5]
The plugin does not import trend/direction information yet. The information is available via LibraLink Up, therefore we should import the values. There probably needs to be a mapping of some sort. 

Nightscout accepts the [following values](https://github.com/nightscout/cgm-remote-monitor/blob/46418c7ff275ae80de457209c1686811e033b5dd/lib/plugins/direction.js#L53):

|  Value  | Symbol  |
|---|---|
|NONE|⇼|
|TripleUp|⤊|
|DoubleUp|⇈|
|SingleUp|↑|
|FortyFiveUp|↗|
|Flat|→|
|FortyFiveDown|↘|
|SingleDown|↓|
|DoubleDown|⇊|
|TripleDown|⤋|
|NOT COMPUTABLE|-|
|RATE OUT OF RANGE|⇕|

**Comment by sebdei** [comment]
#7

**Comment by timoschlueter** [comment]
Thanks again, @sebdei! :)
