### ISSUE TITLE
No LibreLink Up connection found

### ISSUE THREAD

**Issue by ThomasEmge** [timoschlueter/nightscout-librelink-up#59]
I am running into an issue where no link up connection is detected. I believe that is login itself was successful.

I am based in the US and I using the Libre 3 app on Android to upload.

Any suggestions on what else to check or to explore are greatly appeciated.

```
2022-08-10T04:15:00.618200+00:00 app[worker.1]: [info]: Logged in to LibreLink Up
2022-08-10T04:15:00.641332+00:00 app[worker.1]: [error]: No LibreLink Up connection found
```

**Comment by timoschlueter** [comment]
We will figure this out. :)
Do you have data in the actual LibreLink Up Android App available (not the LibreLink App, it needs to be in the LibreLink Up App) with the same account you are using with `nightscout-librelink-up`?

**Comment by ThomasEmge** [comment]
Thanks @timoschlueter . I am new to the Libre ecosytem and I missed that step. I do have a connection now and the values are populated into NightScout as expected. 
Thanks.
