### ISSUE TITLE
Add device name to entries

### ISSUE THREAD

**Issue by timoschlueter** [timoschlueter/nightscout-librelink-up#6]
The "device" attribute is not yet filled. Maybe we can read sensor information from the LibreLink Up API. If not, we should at least fill the "device" attribute with something like `freestyle-libre`

**Comment by job-bens** [comment]
When iI fill in the information as requested the deploy works, but the application does not work no data goes back to Nightscoot

**Comment by timoschlueter** [comment]
This has been added by @swhitt in [v.2.2.0](https://github.com/timoschlueter/nightscout-librelink-up/releases/tag/v2.2.0)
Closing this issue.
