### ISSUE TITLE
Add config options for http/https and TCP-Port

### ISSUE THREAD

**Issue by nightwatcher74** [timoschlueter/nightscout-librelink-up#68]
Hi Timo,

I use you great tool to uplad my data into nightscout which is running on my own docker server and a swarm stack file/compose.
In this case librelink-up and nightscout talk together via a docker (swarm) network directly and i have no https.

Would it be possible to make http/https and the port configurable?

When it will be interesting, heare isma stack file:

version: "3.7"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    domainname: mongo.localdomain.intra
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: <MongoPW>
    networks:
      - nightscout-net
    volumes:
      - /srv/docker/mongo/data:/data/db

  nightscout:
    image: nightscout/cgm-remote-monitor:latest
    container_name: nightscout
    domainname: nightscout.localdomain.intra
    hostname: nightscout
    restart: always
    environment:
      NODE_ENV: production
      TZ: Europe/Berlin
      API_SECRET: <nightscoutSecret>
      MONGO_CONNECTION: mongodb://admin:<mongoPW>@mongo
      INSECURE_USE_HTTP: 'true'
      TIME_FORMAT: 24h
      LANGUAGE: de
      ENABLE: careportal rawbg iob
      AUTH_DEFAULT_ROLES: denied
      HOSTNAME: 0.0.0.0		# required because of IP Service binding
      labels:
        - traefik.enable=true
        - traefik.tags=public
        - traefik.docker.network=traefik-net
        # HTTP to HTTPS redirect
        - traefik.http.routers.nightscout-http.entrypoints=web
        - traefik.http.routers.nightscout-http.rule=Host(`nightscout.localdomain.intra`,`nightscout`,`nightscout.publicdomain.de`)
        - traefik.http.routers.nightscout-http.service=nightscout-http
        - traefik.http.services.nightscout-http.loadbalancer.server.port=1337
        #- traefik.http.routers.nightscout-http.middlewares=nightscout-http		# if https redirect shout be used
        #- traefik.http.middlewares.nightscout-http.redirectscheme.scheme=https
        # HTTPS
        - traefik.http.routers.nightscout-https.entrypoints=websecure
        - traefik.http.routers.nightscout-https.rule=Host(`nightscout.publicdomain.de`)
        - traefik.http.routers.nightscout-https.tls=true
        - traefik.http.routers.nightscout-https.tls.certresolver=myresolver
        - traefik.http.routers.nightscout-https.service=nightscout-https
        - traefik.http.services.nightscout-https.loadbalancer.server.port=1337
    networks:
      - traefik-net
      - nightscout-net
    depends_on:
      - mongo

  nightscout-libre-link:
    image: timoschlueter/nightscout-librelink-up
    container_name: nightscout-libre-link
    hostname: nightscout-libre-link
    restart: always
    environment:
      LINK_UP_USERNAME: "*************"
      LINK_UP_PASSWORD: "*************"
      LINK_UP_TIME_INTERVAL: "5"
      LINK_UP_REGION: "DE"
      NIGHTSCOUT_URL: "nightscout"
      NIGHTSCOUT_API_TOKEN: "<nightscoutSecret>"
      LOG_LEVEL: "debug"
    networks:
      - nightscout-net

networks:
  traefik-net:
    external: true
  nightscout-net:

**Comment by timoschlueter** [comment]
I added an option to disable HTTPS in version `1.9.0`. Set the environment variable `NIGHTSCOUT_DISABLE_HTTPS` to `true` in order to disable HTTPS for Nightscout.
As for the port: You can simply append the port to the `NIGHTSCOUT_URL` (e.g. localhost:8080)

Thank you very much for bringing this up. Its a very useful addition :)
