### ISSUE TITLE
[error]: No LibreLink Up connection found

### ISSUE THREAD

**Issue by akitamostodos** [timoschlueter/nightscout-librelink-up#70]
Hello I use the docker compose: 

version: '3.3'
services:
  nightscout-libre-link:
    image: timoschlueter/nightscout-librelink-up
    container_name: nightscout-libre-link
    environment:
      LINK_UP_USERNAME: "MYEMAIL"
      LINK_UP_PASSWORD: "MYPASSWORD_LIBREVIEW"
      LINK_UP_TIME_INTERVAL: "5"
      LINK_UP_REGION: "EU"
      NIGHTSCOUT_URL: "localhost"
      NIGHTSCOUT_API_TOKEN: "123456789123456789"
      LOG_LEVEL: "info"

And the error on logs is :

> nightscout-librelink-up@1.9.0 start
> node index.js

[info]: Starting cron schedule: */5 * * * *
[info]: no authTicket.expires
[info]: renew token
[info]: Logged in to LibreLink Up
[error]: No LibreLink Up connection found

Can someone help me?

Lot of thanks.

**Comment by timoschlueter** [comment]
@akitamostodos are you sure that you entered the right credentials for LibreLink Up? Don’t confuse the app with the regular LibreLink App. Those are two separate applications in the App Store/Play Store.

This application uses LibreLink Up credentials which are different from the normal one you create in the LibreLink app which you connect your sensor to.

Can you make sure that you provided LibreLink Up credentials via the environment variables?

**Comment by akitamostodos** [comment]
!!!!!!!!!! I feel like stupid!, I was so excited that I didn't read well, LibreLink UP, UP :))) I used the librelink user and password not librelink UP.

  Lot of thanks, and excuse me a lot!.

**Comment by timoschlueter** [comment]
Glad that I could help. It is very confusing, don’t worry :)
