### ISSUE TITLE
Nighscout Port 443/80

### ISSUE THREAD

**Issue by Dabbadoeber** [timoschlueter/nightscout-librelink-up#71]
Is it possible to change the port numbers of the nightscout connection ?
I have nightscout running locally on a synology nas in docker port 80 and 443 are occupied by the nginx server
1337 is the port i use for web interface is it possible to use other ports to upload the data ?
i am new to this so forgive me, as i dont not fully understand everything.
my ultimate goal is to obtain the glucose data in home assistant so at night i can make some automations.

Gr.

**Comment by timoschlueter** [comment]
Yes, this is possible: Just add the Port to your Nightscout URL. 
For example: `nightscout.example.com:1337`
Additionally, you might want to disable the default HTTPS connection by setting the environment variable `NIGHTSCOUT_DISABLE_HTTPS` to `true`.

This should make your setup work :)

**Comment by Dabbadoeber** [comment]
Have tried a lot but no luck,
This is the log file:
[info]: no authTicket.expires
[info]: Logged in to LibreLink Up
info]: -> The following connection will be used: somebody  (Patient-ID: 8723424234234234234234)
error]: connect ECONNREFUSED 172.17.0.4:80
info]: Trying to upload 142 glucose measurement items to Nightscout

NIGHTSCOUT_API_TOKEN - is the the acces token i have in nightscout on the admin page ?

**Comment by timoschlueter** [comment]
Not the main API admin token to access the “Admin Tools”. It’s a separate token you create (a so called “Subject”) via the Nightscout Admin Tools. You can create such token and give it the “admin” role. The returned token is the one you use with this app.

**Comment by Dabbadoeber** [comment]
Thanks, i followed Upload Nightscout fail #15
now i get some data, Thank you for this !

**Comment by timoschlueter** [comment]
Awesome! Glad that you could resolve the problem. :)
