### ISSUE TITLE
Upload to NightScout failed 

### ISSUE THREAD

**Issue by akitamostodos** [timoschlueter/nightscout-librelink-up#72]
Hello, Sute I am doing something bad, but I dont know... If someone can help me.....

yml of the nightscout-librelink-up is:

version: '3.3'
#version: '3.3'

services:
  nightscout-libre-link:
    image: timoschlueter/nightscout-librelink-up
    container_name: nightscout-libre-link
    environment:
      LINK_UP_USERNAME: "USERNAME_LIBRELINK_UP"
      LINK_UP_PASSWORD: "PASSWORD_LIBRELINK_UP"
      NIGHTSCOUT_DISABLE_HTTPS: "true"
      LINK_UP_TIME_INTERVAL: "1"
      LINK_UP_REGION: "EU"
      NIGHTSCOUT_URL: "192.168.0.116" -> LOCAL IP
      NIGHTSCOUT_API_TOKEN: "123456789123456789"
      LOG_LEVEL: "info"

############
############
############
############

the yml of the /nightscout-docker
from the web: [nightscout-docker](https://github.com/nightscout/nightscout-docker)

broker:
  image: 'prologic/mosquitto:latest'
  ports:
    - '1883:1883'
database:
  image: 'tutum/mongodb:latest'
  environment:
    - MONGODB_PASS=123456789123456789

# Uncomment if you want to expose the MongoDB port directly
# If you're using the API interface (highly recommended) then you can 
# safely leave this commented out 
  ports:
    - '27017:27017'

nightscout:
  image: 'nightscout/cgm-remote-monitor-development:latest'
  environment:
    - API_SECRET=123456789123456789
    - 'MONGO_CONNECTION=mongodb://admin:123456789123456789@database/admin'
    - 'MQTT_MONITOR=mqtt://123456789123456789@broker'
    - PORT=1337
  links:
    - broker
    - database
  ports:
    - '1337:1337'

############
############
############

The log is:

[info]: Starting cron schedule: */5 * * * *
[info]: no authTicket.expires
[info]: renew token
[info]: Logged in to LibreLink Up
[info]: Found 1 LibreLink Up connection.
[info]: -> The following connection will be used: NAMEXXXx (Patient-ID: XXXXXXXX)
[error]: self-signed certificate
[info]: Trying to upload 44 glucose measurement items to Nightscout
[error]: self-signed certificate
[error]: Upload to NightScout failed

**Comment by timoschlueter** [comment]
Since you are using docker internal communication, you have to disable HTTPS on your Nightscout container.

Just set the environment variable `INSECURE_USE_HTTP` to `true`. This will make Nightscout listen for unencrypted traffic, which the LibreLink Up container needs in your configuration.

**Comment by akitamostodos** [comment]
Yes, now other error:


[error]: {"message":"Not authorized"}
[error]: Upload to NightScout failed 

I dont know why, I use the api of admin, and now I have created a device I try wit the new api and same error :( frustrating for me:(


Lot of thanks.

**Comment by timoschlueter** [comment]
Have you created a new subject within Nightscouts Admin Tools? You also have to set the “admin” role to the subject and then use the generated token for the Uploader.

**Comment by akitamostodos** [comment]
Yes i did it. And if I put on the web:

http://0.0.0.0:1337/api/v2/authorization/request/device2-67e535026826088a

RETURN:

token	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NUb2tlbiI6ImRldmljZTItNjdlNTM1MDI2ODI2MDg4YSIsImlhdCI6MTY2NjAxMzg3OCwiZXhwIjoxNjY2MDQyNjc4fQ.sTzMS9WEFD8mq5RHNdqZPkE8KN29e4LBveTnm_OoAs8"
sub	"device2"
permissionGroups	
0	
0	"*"
1	[]
iat	1666013878
exp	1666042678


But on the uploader dosnt work

**Comment by emmatovar27** [comment]
I have a similar issue with a local connection! 

I'm using docker to handle everything. 

<img width="376" alt="image" src="https://user-images.githubusercontent.com/39507448/199672426-eda7db16-0962-4376-91ed-42e5e91809e0.png">

I still got the same error. 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/39507448/199672643-1a34399e-aafe-49f3-a635-04638a069228.png">

I have tried: 

- Pass the token or the SHA1 Hash 
- INSECURE_USE_HTTP = true

**Comment by timoschlueter** [comment]
Just to make sure there is no misunderstanding:
If you try to connect the uploader to a local Nightscout instance on the same machine via localhost there are two settings you have to set via environment variables:

---
**Nightscout Docker Container:**
INSECURE_USE_HTTP=true

**LibreLink Up Docker Container:**
NIGHTSCOUT_DISABLE_HTTPS=true
---

Can you please check again that both containers are configured correctly? The settings above disable the HTTPS-requirement on Nightscout itself and additionally makes the uploader access Nightscout through HTTP.

**Comment by emmatovar27** [comment]
Yes! both of the variables are set up correctly. 

![image](https://user-images.githubusercontent.com/39507448/199796790-7fdad221-d5d9-43d3-b05d-2db223823ffb.png)

![image](https://user-images.githubusercontent.com/39507448/199797003-99be6b2b-4689-4fb4-8632-abeb42f09417.png)

Do you think the reason for that is that there are no previous entries? 
![image](https://user-images.githubusercontent.com/39507448/199799192-4f41e093-db0c-4d3e-8a0b-8c218ab0d753.png)

Thanks again!

**Comment by emmatovar27** [comment]
Hey, I fixed it! :) 

I have to change the name from localhost to the container name (nightscout). 

![image](https://user-images.githubusercontent.com/39507448/199838563-83c682ab-272d-4580-9490-77d04d4c3594.png)

Thanks again for this tool! :) I will extract those values to compare them with Dexcom G6.

**Comment by akitamostodos** [comment]
> I have a similar issue with a local connection!
> 
> I'm using docker to handle everything.
> 
> <img alt="image" width="376" src="https://user-images.githubusercontent.com/39507448/199672426-eda7db16-0962-4376-91ed-42e5e91809e0.png">
> 
> I still got the same error.
> 
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/39507448/199672643-1a34399e-aafe-49f3-a635-04638a069228.png">
> 
> I have tried:
> 
> * Pass the token or the SHA1 Hash
> * INSECURE_USE_HTTP = true

OOOKKKK localhost or ip AND PORT!!!! I write the port and works! thanks.

**Comment by timoschlueter** [comment]
@pettermork in your case, the librelink-up container and the nightscout container don't seem to be able to reach each other. This may be the case if both docker containers are not connected to the same docker network. 
Can you tell us where you are hosting the setup and maybe post the entire `docker-compose.yml`?

**Comment by pettermork** [comment]
@timoschlueter
I'm self hosting on my Synology using Portainer to manage my containers. 
(Btw, If anyone else interested to host their own nightscout but is hesitant because it seems like a bit too much there's an excellent walkthrough [here](https://t1d-dzienia-pl.translate.goog/nightscout_synology_tutorial/?_x_tr_sl=pl&_x_tr_tl=en&_x_tr_hl=pl). I know very little about this stuff, which is why I'm here asking questions, but I was able to get it up and running. )

anyhow, my docker-compose.yml looks like this

version: "2"

networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    restart: always
    image: "bitnami/mongodb:4.4.2"
    volumes:
      - "/volume1/docker/data/nightscout/mongodb:/bitnami/mongodb"
    networks:
      - app-tier

  dbbackup:
    restart: always
    image: "tiredofit/db-backup:latest"
    volumes:
      - "/volume1/docker/data/nightscout/backup:/backup"
    environment:
      - COMPRESSION="GZ"
      - COMPRESSION_LEVEL=9
      - DB_TYPE=mongo
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_CLEANUP_TIME=10080
    networks:
      - app-tier

  nightscout:
    restart: always
    image: "nightscout/cgm-remote-monitor:latest"
    environment:
      - API_SECRET=******* #
      - MONGO_CONNECTION=mongodb://mongodb/admin
      - PORT=1337
      - INSECURE_USE_HTTP=false
      - ENABLE=cors careportal boluscalc bwp sage iage iob basal rawbg pushover bgi #
      - DEVICESTATUS_ADVANCED=false
      - AUTH_DEFAULT_ROLES=denied
      - DISPLAY_UNITS=mmol

    networks:
      - app-tier
    ports:
      - 8085:1337 #
      
  nightscout-libre-link:
    image: timoschlueter/nightscout-librelink-up
    container_name: nightscout-libre-link
    environment:
      LINK_UP_USERNAME: *******@gmail.com"
      LINK_UP_PASSWORD: ”******i”
      LINK_UP_TIME_INTERVAL: "5"
      #LINK_UP_REGION: "DE"
      LIBRE_LINK_UP_URL: "api.libreview.io"
      NIGHTSCOUT_DISABLE_HTTPS: true
      NIGHTSCOUT_URL: "192.168.68.131:1337"
      NIGHTSCOUT_API_TOKEN: "******”
      LOG_LEVEL: "debug"

**Comment by pettermork** [comment]
Ok, found the problem. Turned out as so often is the case it was sitting two feet in front of the screen...
Despite it being stated several times in this very thread I had  INSECURE_USE_HTTP set to false 🤦‍♂️.
Anyway, it's working now and I want to thank @timoschlueter for making this.
