### ISSUE TITLE
last glucose dosnt read

### ISSUE THREAD

**Issue by Oscarperez-1980** [timoschlueter/nightscout-librelink-up#73]
Hello, I notice that the last glucose measure, the value of NOW, don't appear, the postbox glucose measures take 20 minutes of delay.
It is right?

Thanks.

**Comment by timoschlueter** [comment]
Could you give a bit more details? Where is the difference visible? Does Nightscout show a different value than the LibreLinkUp App?
I have not come across this issue myself. There is a 5 minute delay between measurements showing up in LibreLinkUp and those measurements being uploaded to Nightscout if you are using the default 5 minute interval.
