### ISSUE TITLE
Calendar Events

### ISSUE THREAD

**Issue by Rtzftz** [timoschlueter/nightscout-librelink-up#77]
Would it be possible to integrate something like the xDrip4iOS "Calendar Events" feature?
Especially for Apple Watch users, the best way to always have the latest blood glucose readings on the watch face is the calendar widget. Due to the lack of Libre3 support, it is currently only possible to configure xDrip as a follower so that it loads the data from nightscout and creates the "calendar event". It would be great if nightscout-librelink-up could take over this task by acting as a caldav client.

**Comment by timoschlueter** [comment]
Hey @Rtzftz, although i really like the idea, i dont think this App is the right place for such a service.
This is something that Nightscout should be handling. For the Apple Watch I am using the "Nightguard"-App. Maybe take a look into it?
