### ISSUE TITLE
High delta

### ISSUE THREAD

**Issue by Samhagberth** [timoschlueter/nightscout-librelink-up#78]
If you compare the delta going up and down ( 5min) its alot higher when you compare with a libre 1 (miaomiao, xdrip4ios) the abbot libre 3 app is compensating down this  afterwords a bit in the logged curve,

Is there a way to apply some average filter on the libre 3 bg values before sending it to nightscout

I think they use something like that in Xdrip4ios.

to prevent the curve to overreach actual bg that leads to sharp turns when changing directions

it will also help againt sudden compression drops and even them out a bit

If your looping it will also be easier for loop to regulate a more stable curve and not give to much and then take away basal all the time

It could be an optional feature

**Comment by Jonaskjellsson** [comment]
Yes, that feature would be great!

**Comment by Kalhama** [comment]
I think this falls out of the scope of this project as this is just a integration between nightscout database and libre. Further data adjustments should be done by nightscout or even further away in the pipeline when nightscout is just used as a database.

**Comment by timoschlueter** [comment]
I agree with @Kalhama. This plugin is just a way of exchanging data. It should be up to the target system to interpret the data. I don't know if there is a way in Nightscout to do this kind of data processing, but it's certainly out of scope for this plugin. Sorry!
