### ISSUE TITLE
connection problems

### ISSUE THREAD

**Issue by markus31rbg** [timoschlueter/nightscout-librelink-up#80]
kann mir jemand bei meinen Problem helfen ???
ich bekomme folgende Meldung.
Danke. 

> nightscout-librelink-up@1.9.0 start
> node index.js

[info]: Starting cron schedule: */1 * * * *
[info]: no authTicket.expires
[info]: renew token
[info]: Logged in to LibreLink Up
[error]: getting libreLinkUpConnection:  Cannot read properties of undefined (reading 'token')

**Comment by cubybox** [comment]
Hatte gerade das gleich Problem. Habe mich dann in der Libre Linkup-App einmal ab- und angemeldet. Musste bei der Wiederanmeldung einmal Nutzungsbedingungen akzeptieren - danach lief dann auch die Anmeldung mit diesem Tool wieder.

**Comment by pyrmon** [comment]
Thanks for the answer. I was very confused why nothing was working anymore! 👍

**Comment by pettermork** [comment]
I had the same problem. Logging out from the LibreLink Up app and then back in solved it.
