### ISSUE TITLE
Process exited with status 0

### ISSUE THREAD

**Issue by sfgul** [timoschlueter/nightscout-librelink-up#83]
hello
I am getting the values at 11 minute intervals.
I couldn't understand the errors it gave. it gives this error every time a value is loaded..What should I do?

log:

> 2022-12-27T20:52:38.840149+00:00 heroku[worker.1]: Process exited with status 0
> 2022-12-27T20:52:38.885052+00:00 heroku[worker.1]: State changed from up to crashed
> 2022-12-27T21:03:33.880472+00:00 heroku[worker.1]: State changed from crashed to starting
> 2022-12-27T21:03:36.811904+00:00 heroku[worker.1]: Starting process with command `npm start`
> 2022-12-27T21:03:37.433165+00:00 heroku[worker.1]: State changed from starting to up
> 2022-12-27T21:03:39.490209+00:00 app[worker.1]: 
> 2022-12-27T21:03:39.490231+00:00 app[worker.1]: > nightscout-librelink-up@1.9.1 start
> 2022-12-27T21:03:39.490231+00:00 app[worker.1]: > node index.js
> 2022-12-27T21:03:39.490232+00:00 app[worker.1]: 
> 2022-12-27T21:03:39.635782+00:00 app[worker.1]: [info]: no authTicket.expires
> 2022-12-27T21:03:39.636195+00:00 app[worker.1]: [info]: renew token
> 2022-12-27T21:03:40.309196+00:00 app[worker.1]: [info]: Logged in to LibreLink Up
> 2022-12-27T21:03:40.708399+00:00 app[worker.1]: [info]: Found 1 LibreLink Up connection.

**Comment by timoschlueter** [comment]
Can you provide some more details? Especially the ENVIRONMENT variables you have set would be very useful resolving your problems :)

**Comment by sfgul** [comment]
thank you very much for your answer

LINK_UP_REGION = DE
LINK_UP_TIME_INTERVAL = 5 (I tried as 1, the situation did not change
LOG_LEVEL = info
NIGHTSCOUT_DISABLE_HTTPS = true
SINGLE_SHOT = true

**Comment by timoschlueter** [comment]
There have been a few improvements regarding logging in version 2.2.0. Could you please check if this is still an issue for you?
