### ISSUE TITLE
LibreLinkUp Update 4.7

### ISSUE THREAD

**Issue by Jonaskjellsson** [timoschlueter/nightscout-librelink-up#99]
Hi LibreLinkUp will be updated to version LibreLinkUp 4.7.

All older versions will stop working on 6/21
Will Nightscout LibreLink Up work after 6/22?

**Comment by mielleman** [comment]
I share the same worry as @Jonaskjellsson, based on the email we got it seems that the API will change and that after June 21st we might be blocked.

**Comment by pettermork** [comment]
Seems mine broke last night, I get a NOAuth Ticket recieved error.

**Comment by mielleman** [comment]
> Seems mine broke last night, I get a No AuthTicket recieved error.

I think you need to accept the new agreement, go to your phone, logout of LibreLinkUp and log back in. You should get the new agreement, then accept it. Afterwards, getting a token should work again.

**Comment by pettermork** [comment]
Yes of course, I forget it every time that happens.

**Comment by timoschlueter** [comment]
Hi everyone! Since I don't have access to the update in advance or any other documentation we might run into a the situation that this app needs to be updated when the new LLU version is released.

I will do my best to keep the downtime as short as possible. Unfortunately we need to actually look at the updated API in order to see how much we need to change.

Nevertheless I am confident that we well be able to keep using this app. Just prepare for a day or two without data.

**Comment by mielleman** [comment]
Thanks for responding @timoschlueter, if needed I am very much willing to help.

**Comment by yaronkhazai** [comment]
Hello @timoschlueter, is there any progress? If needed I can also try to help, please let me know

**Comment by alinadrian2391** [comment]
I am getting the glucose data with ~20 min delay on LinkUpApp, anybody else?

**Comment by david-lively** [comment]
I'm also seeing ~20-30 minute delays (US, iPhone). The LibreLinkUp app on my phone also isn't working, just says "An error occurred please try again later." Yay, Abbot.

**Comment by timoschlueter** [comment]
Seems like 4.7.0 has just been released to the App Store. I downloaded the app a few minutes ago and so far _nightscout-librelink-up_ seems to still be working just fine.

Can somebody else confirm this?

**Comment by david-lively** [comment]
I had to uninstall the app and re-install it. It's now showing 4.7.0. NLU appears to be working, but the readings are still lagging on nightscout (as they are in the LibreLinkUp app, so that's not an issue with NLU.)

**Comment by david-lively** [comment]
Seeing some interesting things in the logs now. It was successfully pushing updates to nightscout, now getting a JS error.

**Comment by pettermork** [comment]
I updated just now (from Swedish AppStore), and so far no problems. I did not experience any lagging updates to NS earlier either.

**Comment by timoschlueter** [comment]
I just finished analysing the traffic between LLU version 4.7.0 and Abbotts infrastructure. The APIs seem to still be compatible with _nightscout-librelink-up_. Only minor changes have been added in version 2.4.0 just to be safe. You can see the details in PR #101. 

Version 2.4.0 should be available to download on GitHub and Docker Hub within the next hour. :)

**Comment by timoschlueter** [comment]
I have not yet experienced any lags on the update (neither on 4.7.0, nor the previous version). I am using the DE region since i am located in germany. Can we find a common region that is having issues?

**Comment by david-lively** [comment]
The nature of the errors coming from their API and from the LibreLinkUp app have changed throughout the day. I suspect they're still rolling out and, in true IT professional fashion, doing it badly. Given that their own app isn't working with their servers in the US at the moment, I doubt there's anything that can be done on this end.

**Comment by david-lively** [comment]
@timoschlueter Thanks for looking into this. This package has made my life a lot easier over recent months.

**Comment by alinadrian2391** [comment]
> I have not yet experienced any lags on the update (neither on 4.7.0, nor the previous version). I am using the DE region since i am located in germany. Can we find a common region that is having issues?

I am in US and the lag is still here

**Comment by david-lively** [comment]
Same here. (US)

**Comment by david-lively** [comment]
They're definitely still updating things. Everything was running fine for about half an hour (albeit still with the lag), and then it started generating errors:
```
 2023-06-15T21:36:00.928 app[e784e76dc21468] dfw [info] [info]: No new measurements to upload

2023-06-15T21:39:00.517 app[e784e76dc21468] dfw [info] [info]: Found 1 LibreLink Up connection.

2023-06-15T21:39:00.517 app[e784e76dc21468] dfw [info] [info]: -> The following connection will be used: Steven Lively (Patient-ID: f61a895e-d8f5-11eb-844d-0242ac110004)

2023-06-15T21:39:01.131 app[e784e76dc21468] dfw [info] [info]: Trying to upload 1 glucose measurement items to Nightscout

2023-06-15T21:39:01.514 app[e784e76dc21468] dfw [info] [info]: Upload of 1 measurements to Nightscout succeeded

2023-06-15T21:42:00.760 app[e784e76dc21468] dfw [info] [error]: {"data":{"minimumVersion":"4.7.0"},"status":920}

2023-06-15T21:42:00.767 app[e784e76dc21468] dfw [info] [error]: getting libreLinkUpConnection: Cannot read properties of undefined (reading 'data')

**Comment by david-lively** [comment]
The plot thickens. I ran this with logLevel `debug` locally. I haven't looked at the request we're sending to their server, but it would appear that they're somehow determining that we're not using the current "4.7.0" . Losers. 
```
➜  nightscout-librelink-up git:(main) ./start.sh

> nightscout-librelink-up@2.2.0 start
> npx ts-node --transpile-only src/index.ts

[info]: Starting cron schedule: */1 * * * *
[info]: renew token
[info]: Logged in to LibreLink Up
[debug]: authenticatedHttpHeaders: {"User-Agent":"FreeStyle LibreLink Up NightScout Uploader","Content-Type":"application/json","version":"4.2.2","product":"llu.ios","Accept-Encoding":"gzip, deflate, br","Connection":"keep-alive","Pragma":"no-cache","Cache-Control":"no-cache","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY2MWE4OTVlLWQ4ZjUtMTFlYi04NDRkLTAyNDJhYzExMDAwNCIsImZpcnN0TmFtZSI6IlN0ZXZlbiIsImxhc3ROYW1lIjoiTGl2ZWx5IiwiY291bnRyeSI6IlVTIiwicmVnaW9uIjoidXMiLCJyb2xlIjoicGF0aWVudCIsInVuaXRzIjoxLCJwcmFjdGljZXMiOltdLCJjIjoxLCJzIjoibGx1LmlvcyIsImV4cCI6MTcwMjQxODgyMX0.s5QzRc0N2YyihF2bhlBYf7ATi1p6EPi1sJw1eEPZmUw"}
[error]: {"data":{"minimumVersion":"4.7.0"},"status":920}
[error]: getting libreLinkUpConnection:  Cannot read properties of undefined (reading 'data')
[info]: renew token
[info]: Logged in to LibreLink Up
[debug]: authenticatedHttpHeaders: {"User-Agent":"FreeStyle LibreLink Up NightScout Uploader","Content-Type":"application/json","version":"4.2.2","product":"llu.ios","Accept-Encoding":"gzip, deflate, br","Connection":"keep-alive","Pragma":"no-cache","Cache-Control":"no-cache","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY2MWE4OTVlLWQ4ZjUtMTFlYi04NDRkLTAyNDJhYzExMDAwNCIsImZpcnN0TmFtZSI6IlN0ZXZlbiIsImxhc3ROYW1lIjoiTGl2ZWx5IiwiY291bnRyeSI6IlVTIiwicmVnaW9uIjoidXMiLCJyb2xlIjoicGF0aWVudCIsInVuaXRzIjoxLCJwcmFjdGljZXMiOltdLCJjIjoxLCJzIjoibGx1LmlvcyIsImV4cCI6MTcwMjQxODg4MH0.KCwJYznmR1uwPLOlPVmpTuA4h7BEPjGmJ_5SjTJL6xo"}
[error]: {"data":{"minimumVersion":"4.7.0"},"status":920}
[error]: getting libreLinkUpConnection:  Cannot read properties of undefined (reading 'data')

**Comment by david-lively** [comment]
Success! Changing the rev from `4.2.2` to `4.7.0` in `index.ts` has fixed the error for me. The lag is still there, but the `Cannot read properties...` mess is corrected.

**Comment by david-lively** [comment]
Unfortunately, I can't branch or submit a PR for this. But, just go into `index.ts` and replace `4.2.2` with `4.7.0` and this immediate issue disappears.

**Comment by xsen84** [comment]
Not sure how this might be related but after pulling the latest version i get this:

nightscout-librelink-up@2.4.0 start /home/alexandru_mihai84/nightscout-librelink-up
npx ts-node --transpile-only src/index.ts

/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:76
  #loaded = false
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/config/definition.js:34:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by stncttr908** [comment]
Update worked great, thank you so much for your efforts! My updates are still lagging by 20+ minutes, but that's a LibreLink problem.

**Comment by david-lively** [comment]
As of 10:55 CST, LibreLinkUp is working again, as is Nightscout-LibreLink-Up, NightScout and, thus, Loop. I'm in DFW (US), so not sure if it'll take longer for the changes to roll out to other US zones. Also, make sure you're using the latest `main` that @timoschlueter pushed earlier today to update to the 4.7.0 API version header. 

Also, hello from Dallas, TX. Be safe, friends.

**Comment by Ederborg** [comment]
Hello!
Im getting this error after the update in Sweden. Am I doing anything wrong?

[info]: no authTicket.expires
[info]: renew token
[info]: Logged in to LibreLink Up
[error]: {"data":{"minimumVersion":"4.7.0"},"status":920}
[error]: getting libreLinkUpConnection:  Cannot read properties of undefined (reading 'data')

**Comment by timoschlueter** [comment]
@Ederborg I released version 2.4.0  yesterday. This version should fix your problem. Although I don't receive any data here in Germany right now. But that might still be a problem with Abbotts infrastructure.

Just try the new version 2.4.0 and your error should be gone :)

**Comment by Ederborg** [comment]
> @Ederborg I released version 2.4.0 yesterday. This version should fix your problem. Although I don't receive any data here in Germany right now. But that might still be a problem with Abbotts infrastructure.
> 
> Just try the new version 2.4.0 and your error should be gone :)

Thank you! It has been working fine for so long I haven't done anything to it :) Including updating anything!

**Comment by mielleman** [comment]
> @Ederborg I released version 2.4.0 yesterday. This version should fix your problem. Although I don't receive any data here in Germany right now. But that might still be a problem with Abbotts infrastructure.
> 
> Just try the new version 2.4.0 and your error should be gone :)

I am in Germany as well, 2.4.0 works for me and I am receiving data again. I had to update due to receiving `{"minimumVersion":"4.7.0"}` after my LibreLinkUp app on my phone was updated.

**Comment by timoschlueter** [comment]
For me there is no data at all since last night. I have no idea what happened but even the LLU app does not show anything anymore. 
I guess I have to wait till Abbott  has things sorted out.

But I am very glad to hear the my update yesterday works for you all! :)

**Comment by yaronkhazai** [comment]
Hi

following the thread here
i just changed this line
const LIBRE_LINK_UP_VERSION = "4.7.0";
and everything is working perfectly 
i am using the DE endpoint

thanks

**Comment by Havanna22** [comment]
2.4.0 doesn't work for me, unfortunately. Still no data.
Will there be a build with that const corrected for english version? I am not used to making my own builds, not possible for me to learn right now.

**Comment by timoschlueter** [comment]
@yaronkhazai thats what I changed with v2.4.0. Maybe you can just update to the latest version. It should work as well :)

**Comment by timoschlueter** [comment]
@Havanna22 you can always go back to a previous release of this app. All versions are available for download on here under the "Releases" tab as well as the global Docker Hub container registry. I won't delete older version exactly for those backwards compatibility reasons.

**Comment by buzlachok** [comment]
Thank you. Updated applications and agreement. Code too. But at startup it says: Unexpected token ?

> npx ts-node --transpile-only src/index.ts
Unexpected token ?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nightscout-librelink-up@2.4.0 start: `npx ts-node --transpile-only src/index.ts`
npm ERR! exit status 1


What does this mean?

**Comment by Havanna22** [comment]
Neither previous version of the app, nor the latest (2.4.0) works, unfortunately.
So there's something more wrong

**Comment by timoschlueter** [comment]
@Havanna22 when was the last time it worked for you? Maybe we can find out. 

As of 10 minutes ago I am receiving values in LLU again and in _nightscout-librelink-up_ as well :)

**Comment by jeremyhipp** [comment]
@timoschlueter The v2.4.0 docker container using docker-compose fails to start on my system with the following error:
```
Starting nightscout-libre-link
Attaching to nightscout-libre-link
nightscout-libre-link    | node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
nightscout-libre-link    |  1: 0xb7a940 node::Abort() [node]
nightscout-libre-link    |  2: 0xb7a9be  [node]
nightscout-libre-link    |  3: 0xbe98be  [node]
nightscout-libre-link    |  4: 0xbe99a1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
nightscout-libre-link    |  5: 0xb38f5b node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
nightscout-libre-link    |  6: 0xb395ab node::Start(int, char**) [node]
nightscout-libre-link    |  7: 0x7f2e0bcb418a  [/lib/x86_64-linux-gnu/libc.so.6]
nightscout-libre-link    |  8: 0x7f2e0bcb4245 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
nightscout-libre-link    |  9: 0xabbdee _start [node]
nightscout-libre-link exited with code 139
```

The v2.3.0 container launches correctly.

**Comment by timoschlueter** [comment]
@jeremyhipp: which platform are you using? some sort oft raspberry pi maybe?

**Comment by jeremyhipp** [comment]
@timoschlueter I'm running on a VPS with Ubuntu 16.04, 4 cores (<10% load), 8GB RAM (~5.5 GB free). It could very well be the old Ubuntu version, I was just surprised it stopped since v2.3.0 ran fine.

**Comment by maddox** [comment]
> The v2.4.0 docker container using docker-compose fails to start on my system with the following error 

I'm getting the same on an Ubuntu 20.04 host.

**Comment by timoschlueter** [comment]
I am setting up a VPS with Ubuntu 20.04 on AWS Lightsail right now. Maybe I can reproduce the problem there.

**Comment by timoschlueter** [comment]
This might be related to this issue: https://github.com/nodejs/node/issues/43064
I will look into it.

**Comment by timoschlueter** [comment]
@maddox and @jeremyhipp: version 2.4.1 should fix your problems. 
The new version will be available in about 30 minutes on Docker Hub.

**Comment by maddox** [comment]
Looks good now! Thanks so much. Incredible support for something you're doing in your off time. We all really appreciate it. It's amazing how important this project has become for me so I can get my numbers on my watch face, which has become a big deal for me.

Thanks!

**Comment by timoschlueter** [comment]
Thank you so much @maddox, I really appreciate the kind words and the sponsorship! I will do my best to keep this app going since it made life so much easier for myself as well. :)

**Comment by david-lively** [comment]
+1000 This app is the only way I've been able to get Loop working reliably without shutting down in the background (iPhone). It's a life saver. In a perfect world, we wouldn't have to have data go from the phone, to Abbot's servers, to Nightscout, and back to the phone just to get a few numbers from the Libre app to the Loop app, but... I'm grateful for any solution that works. 
This is awesome work.

**Comment by zreptil** [comment]
This is really really great. Thank you so much for your work. Up to now i had no clue, how this works, but since ns10.be.de is still not uploading the data, i gave the local installation a try and it works. My windows pc has to run, so that this can be uploaded, but since i only need this temporary when Abbot decides again to annoy his customers or to make the process of running the follower still more intransparent and cumbersome, this works for me. Thanks again, Timo. This is brilliant 👍

**Comment by maddox** [comment]
This is in no way an advertisement, and it's certainly off topic, but with everyone expressing how important this data is...I thought it might be worth a mention.

I built a simple tool that works like this project, that will read from Nightscout and publish it online to Amazon S3 in a way that Nightscout clients can read from it. 

I did this because I self host Nightscout, and do not have any holes in my firewall for things to access it, I use a VPN instead. Using my project lets you point mobile clients at the endpoint on S3, so they can get the data, without having to access your home network. I use this specifically with [Gluco Tracker](https://github.com/HanSolo/Gluco-Tracker) to get my number on my watch face via a complication.

So, I hope this might help someone else!

**Comment by timoschlueter** [comment]
@maddox: This is also looks like a great way to archive Nightscout data! Didn't know that existed! Awesome. Thank you for sharing!

@zreptil: Thank you so much. I really appreciate the kind words! :)

**Comment by cabbage2400** [comment]
> @maddox / @jeremyhipp: the update is available. can you verify that it works for you?
> 
> @cabbage2400: I set up a zoom meeting you should be able to join. I will be here for about an hour :) https://us05web.zoom.us/j/89858968770?pwd=Z3pyNFFhQkp0MjBKQUh0U0RYelRFUT09

Shoutout to Timo for hopping on zoom and fixing this for me. Thank you so much!!!!!!

**Comment by moulicka** [comment]
Hi, thank you for your great work timoschlueter!
I need some advice on how to easily find the patient ID. I used https://api-eu.libreview.io/
, but it doesn't work now and I can't see the Patient ID in the account settings. The instructions say to use the console, what exactly is it and where can I find it?
thank you very much

**Comment by timoschlueter** [comment]
@moulicka: where did you host the app? On Heroku you can watch the "Logs" of the app from the console. If you have deployed the app via Docker, the patient-ids are logged to the console. Unfortunately, the Patient-ID is not easily visible from within an official webinterface. Thats why we log it to the console if you start the app without a patient-id set.

**Comment by moulicka** [comment]
aha, that's a simple solution,  I'll try it. Thanks a lot for the advice.
I use Postman for the statement. In the end, I had the error in the specified version (I fixed it to 4.7.0) now it works.
Thanks again for the quick reply and advice!

**Comment by kimsol1** [comment]
Hi

I haven't got any data to my nightscout for about a month. When I look att deployment logs I get these errors which I didn't get before (previous to the update in june):

﻿> nightscout-librelink-up@1.9.0 start
﻿> node index.js
﻿[info]: Starting cron schedule: */5 * * * *
﻿[info]: no authTicket.expires
﻿[info]: renew token
﻿[info]: Logged in to LibreLink Up
﻿[error]: {"data":{"minimumVersion":"4.7.0"},"status":920}
﻿[error]: getting libreLinkUpConnection:  Cannot read properties of undefined (reading 'data')

Anybody that has any idea what I need to do to get the readings from Libre working again?

**Comment by david-lively** [comment]
@kimsol1 That's due to an update that Abbott deployed about a month ago. Pull the latest of this repo and re-deploy it. The only real change is updating the version number for the LLU API calls.

**Comment by david-lively** [comment]
> 

I'm using Fly.io for hosting. It's free at this tier and has been working without a hitch for a few months now.

**Comment by ManuelNegreteGarrido** [comment]
hola comunidad, algun librelink up para escritorio o alguna alternativa para que mis registros lleguen directo a mi mac??

muchas gracias.

**Comment by PieCaptain** [comment]
hello, please accept my apologies in advance if this is an incredibly silly question, but...

this evening I setup nightscout on azure as per the instructions here - https://nightscout.github.io/vendors/azure/new_user/#

I have my librelink updating to librelinkup 

but have absolutely no idea how to use this to link librelinkup to nightscout, can anyone point me in the right direction?

From the description here: "this image can be easily added to your existing docker-compose file"

i guess that's what I need to do, I've tried google, but i don't understand the results I get back! (sorry!)

Thank you in advance!

**Comment by DiLoT2D** [comment]
hallo ... does anybody have a "howto" to install this on "https://ssh.cloud.google.com" ..... Nightscout is already running
Thx in advance
